### ISSUE TITLE
How do I install 3rd party dependencies for my locustfile.py?

### ISSUE THREAD

**Issue by markyberbenzana** [apardo04/locust-github-action#1]
Everytime I need to run my script I have to deliberately disable third-party dependencies that are not related to locust. How can I apply this when running locust-github-action?

**Comment by apardo04** [comment]
Hello, can you give me an example of your locustfile? Also, does this locustfile work when not using my action?

**Comment by markyberbenzana** [comment]
Hi @apardo04, yes when I run the locustfile in my local it's working. Because I have the dependencies installed in my virtual env. I thought if I install and cached my dependencies via requirements.txt it will work, but I think because your action deploys it in docker the dependencies are not used on the workflow job. Here's a snippet sample of my `locustfile.py`:
```
import os
from dotenv import find_dotenv, load_dotenv
from locust import HttpUser, task, between

class PerformanceRun(HttpUser):
    wait_time = between(120000, 600000)

    @task
    def broadcast_main(self):
         phone_num = os.getenv('PHONE_NUM')
         response = self.client.post("/user/login", json={"country_code": "+86", "cellphone": phone_num})
```

When I try to run it on your action, an error is thrown for using `dotenv` because it's a third-party dependency for `.env` files

**Comment by apardo04** [comment]
Hello @markyberbenzana , I'm sorry for the late response. Have you tried adding the dependency to the Dockerfile?

For example, I do `RUN pip install locust==1.0.1`. You should be able to do the same with your 3rd party dependencies at this stage.

Having the action automatically do this, would be a great enhancement. I will add this feature when I get some more time!

**Comment by markyberbenzana** [comment]
I haven't tried that, I went with the CLI approach instead. Works the same thing although this could have been more convenient. Will try your suggestion as well.
