### ISSUE TITLE
Using locust-github-action with username and password secrets

### ISSUE THREAD

**Issue by gholin** [apardo04/locust-github-action#2]
Hey there.

I am using your github actions to run locust load tests. I'm running into one security issue though.

Basically I don't want to store passwords in my repo, so I was thinking of storing my password in a github env secret and use it with your action as an env variable that my code can pull in when running my locustfile in github actions.

I noticed that your action doesn't support username and password inputs. Is this something you can add as optional inputs to the action? Thanks!

**Comment by apardo04** [comment]
Hello,

Please see this branch as an example: https://github.com/apardo04/locust-github-action/tree/env-var-test

1. I created a repository secret in the Github UI
2. Assigned it to an env variable 'GITHUB_USERNAME' in my workflows yml file: https://github.com/apardo04/locust-github-action/blob/env-var-test/.github/workflows/test.yml
3. Referenced the env variable in locustfile: https://github.com/apardo04/locust-github-action/blob/env-var-test/locustfile.py

Hope this helps!

**Comment by gholin** [comment]
That helped a ton! I have it working now in my repo. Thank you @apardo04!
