### ISSUE TITLE
How to pass range of a users, rate, runtime in this script 

### ISSUE THREAD

**Issue by vipin-discovery** [apardo04/locust-github-action#3]
Hi @apardo04

I am trying to execute the script by passing specific range of users in my test.yml file but i am getting error. I have declared env variables for it then i am getting error like locustfile, users, rate, runtime is not recognised 

exact error i am getting like: Unexpected input(s) 'LOCUSTFILE', 'URL', 'USERS', 'RATE', 'RUNTIME', valid inputs are ['repository', 'ref', 'token', 'clean', 'submodules', 'lfs', 'fetch-depth', 'path'] 

could you please give me your input here?

**Comment by apardo04** [comment]
Hello,

Few questions:

1. What do you mean by "passing specific range of users"?
2. Where/how did you declare your env variables?
3. Do you know at what step the error is coming from?

**Comment by vipin-discovery** [comment]
@apardo04 

1.I am able to pass any inputs while manually triggering the pipeline manually for locust by removing options to string so that what input user will give while manually triggering the pipeline should get executed on behalf only.

2. i have created .env file but i don't think this is good way i think we can declare our env variables in entrypoint file.
This all below values i want to pass as variable could you please help me on this. 
**Note:** string value required so that user can pass any value while manually triggering the pipeline.

LOCUSTFILE: "locustfile.py"
          URL:  "https://prod.playback.h264.io" 
          USERS: "6"
          RATE: "6"
          RUNTIME: "10s"


3.  i am getting error below error
locust: error: argument -H/--host: expected one argument...


Here is my test.yml  file 


name: Running Locust Load Test

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'target environment'
        required: true
        type: string
        default: "github"
      host:
        required: true
        type: string
        options:
          - https://prod.playback.h264.io
        default: "https://prod.playback.h264.io"
        description: "  "
      endpoint:
        required: true
        type: string
        default: "integration"
        description: "endpoint"
      users:
        required: true
        type: string
        default: "5"
        description: "Number of users"
      spawn-rate:
        description: "spawn-rate"
        type: string
        required: true
        default: "5"
      run-time:
        description: 'run-time'
        type: string
        required: true
        default: "10s"
    push:
      branches:
      - main
      - test
      - dev 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run Load Test
        uses: vipin-discovery/Demo-Load@dev
        with:
          LOCUSTFILE: ${{ github.event.input.locust1file }}
          URL:  ${{ github.event.input.URL }}
          USERS: ${{ github.event.inputs.users }}
          RATE: ${{ github.event.inputs.spawn-rate }}
          RUNTIME: ${{ github.event.inputs.run-time }}

my .env file have below values:

LOCUSTFILE = locustfile.py
URL = "https://prod.playback.h264.io"
RATE = "  "
USERS = "  "
RUNTIME = "  "

**Comment by apardo04** [comment]
Do you have code somewhere that I can pull with the issue reproduced?

**Comment by apardo04** [comment]
Please reopen if you still need assistance.
